blank_issues_enabled: false
contact_links:
  - name: DAO Community Forum
    url: https://forum.example.com
    about: Please ask general questions here.
  - name: Documentation
    url: https://docs.example.com
    about: Check our documentation for guides and examples.
